export default {
    root: '/',
    workPlan: '/workplan',
    workPlanEdit: '/workplan?edit=1',
    login: '/login',
    logout: '/logout',
    settings: '/settings',
    employeeManagement: '/management-employee',
    employeeDetails: '/employee',
    productManagement: '/management-product',
    productDetails: '/product',
    productionReport: '/report/production',
    productionReportList: '/report/production/reports',
    productionReportDetail: '/report/production/report',
    lineManagement: '/management-line',
    lineDetails: '/line',
    userManagement: '/management-user',
    userDetails: '/user',
}