export default {
    root: '/hextl',
    workPlan: '/hextl/workplan',
    workPlanEdit: '/hextl/workplan?edit=1',
    login: '/hextl/login',
    logout: '/hextl/logout',
    settings: '/hextl/settings',
    employeeManagement: '/hextl/management-employee',
    employeeDetails: '/hextl/employee',
    productManagement: '/hextl/management-product',
    productDetails: '/hextl/product',
    productionReport: '/hextl/report/production',
    productionReportList: '/hextl/report/production/reports',
    productionReportDetail: '/hextl/report/production/report',
    lineManagement: '/hextl/management-line',
    lineDetails: '/hextl/line',
    userManagement: '/hextl/management-user',
    userDetails: '/hextl/user',
}